services:
  nestapp:
    container_name: appointment-app
    image: appointment:1.0.0
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=mysql
      - USER=root
      - PASSWORD=root
      - DB=interview
      - PORT=3306
      - HOST=db
    depends_on:
      - db
  db:
    container_name: appointment-db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=interview
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init-db-script/:/docker-entrypoint-initdb.d/
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']  
volumes:
  my-db: